auth_app/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import signup, main_user_page

app_name = 'auth_app'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='auth_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('main/', main_user_page, name='main_user_page'),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='auth_app/password_reset.html',
            email_template_name='auth_app/password_reset_email.html',
            subject_template_name='auth_app/password_reset_subject.txt',
            success_url='done/',
            # success_url=reverse_lazy('auth_app/password_reset_done'),
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='auth_app/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='auth_app/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='auth_app/password_reset_complete.html'),
        name='password_reset_complete'),
    #
    url(r'^settings/password/$',
        auth_views.PasswordChangeView.as_view
        (template_name='auth_app/password_change.html',
         success_url='done/'
         ),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='auth_app/password_change_done.html'),
        name='password_change_done'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from django.conf.urls import include, url
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('auth_app.urls')),
    path('api/v0/', include('api_v0.urls')),
    path('debug/', include(debug_toolbar.urls))
]

shop/urls.py
from django.conf.urls import url

from .views import *
from .api import api

app_name = 'shop'
urlpatterns = [
    url(r'^$', IndexListView.as_view(), name='index'),
    url(r'^subcategory/(?P<pk_subcategory>\d+)/$', SubcategoryProductListView.as_view(),
        name='subcategory_product'),
    url(r'^subcategory/(?P<pk_product>\d+)/details/$', ProductDetailsView.as_view(),
        name='product_details'),
    url(r'^add-to-session/$', AddProductToSessionView.as_view(),
        name='add_to_session'),
    url(r'^remove-product-from-session/$', RemoveProductFromSessionView.as_view(),
        name='remove_from_session'),
    url(r'^remove-all-products-from-session/$', RemoveAllProductsFromSession.as_view(),
        name='remove_all_products'),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^order/$', MakeOrderView.as_view(), name='order'),
    url(r'^api/$', api),
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models

from base import settings


class Category(models.Model):
    title = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title


class Subcategory(models.Model):
    category = models.ManyToManyField(Category, related_name="subcategories")
    title = models.CharField(max_length=200, db_index=True)

    class Meta:
        verbose_name_plural = "Subcategories"

    def __str__(self):
        return self.title


class Currency(models.Model):
    name_currency = models.CharField(max_length=10, default="USD")
    UAH = models.CharField(max_length=3, default="UAH")
    currency_exchange = models.DecimalField(max_digits=8, decimal_places=0, default=25)

    class Meta:
        verbose_name_plural = "Currencies"

    def __str__(self):
        return self.name_currency


class Product(models.Model):
    subcategory = models.ManyToManyField(Subcategory)
    currency_pk = models.ForeignKey(Currency, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    description = models.TextField()
    amount = models.IntegerField(default=20)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    image_url = models.CharField(
        max_length=100, default="https://s3.amazonaws.com/django-shop-stuff/"
    )
    on_the_main = models.BooleanField(default=False)
    sku = models.CharField(max_length=10, default="200000")
    meta_keywords = models.CharField(max_length=100, db_index=True, blank=True)
    meta_description = models.CharField(max_length=1000, db_index=True, blank=True)

    __text_desription = """{} - 
     купить на django-shop-test.herokuapp.com: 
    050 123 45 67. Оперативная доставка 
    Гарантия качества
    Лучшая цена $ """

    def save(self, *args, **kwargs):
        if not self.meta_keywords or not self.meta_description:
            self.meta_keywords = self.title
            self.meta_description = self.__text_desription.format(self.title)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_total_price_in_ua(self):
        return self.price * self.currency_pk.currency_exchange


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    product_fk = models.ManyToManyField(Product)
    name_user = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=20)
    email_user = models.EmailField(max_length=100)
    total_price = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total_count = models.IntegerField()
    order_date = models.DateTimeField(auto_now_add=True)
    product_ids = models.CharField(max_length=200)

    def __str__(self):
        return self.name_user

shop/forms.py
from django import forms
from django.forms import ModelForm, CharField

from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["name_user", "phone_number", "email_user"]
        labels = {"name_user": ("Your name")}
        help_texts = {"name_user": ("Your full name")}
        error_messages = {"name_user": {"max_length": ("This writer's name is too long.")}}

shop/views.py
from base.settings import EMAIL_HOST_USER
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, View

from .forms import OrderForm
from .for_email import answer_email
from .helpers import (
    products_total_price_amount,
    remove_amount_products_from_db,
    remove_all_products_from_session,
)
from .models import Product, Subcategory, Order
from .tasks import send_message_on_email


class IndexListView(ListView):
    queryset = Product.objects.filter(on_the_main=True).order_by("id")
    context_object_name = "products"
    template_name = "shop/index.html"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        page = self.request.GET.get("page", 1)
        paginator = Paginator(self.queryset, self.paginate_by)
        context = {}
        try:
            products_on_page = paginator.page(page)
            context = {
                "subcategory": products_on_page,
                "products": self.request.session.get("products", []),
                "amount_each": self.request.session.get("amount", {}),
            }
        except PageNotAnInteger:
            context["subcategory"] = paginator.page(1)
        except EmptyPage:
            context["subcategory"] = paginator.page(paginator.num_pages)

        return context


class SubcategoryProductListView(ListView):
    def get(self, request, pk_subcategory):
        products_in_subcategory = (
            Product.objects.select_related("currency_pk")
            .filter(subcategory__in=pk_subcategory)
            .order_by("id")
        )
        page = request.GET.get("page", 1)
        paginator = Paginator(products_in_subcategory, 6)
        context = {}
        # UAH = products_in_subcategory.select_related('currency_pk').filter(UAH='UAH')
        try:
            products_on_page = paginator.page(page)
            context = {
                "subcategory": products_on_page,
                "subcategory_name": get_object_or_404(Subcategory, id=pk_subcategory),
                "products": request.session.get("products", []),
                "amount_each": request.session.get("amount", {}),
            }
        except PageNotAnInteger:
            context["subcategory"] = paginator.page(1)
        except EmptyPage:
            context["subcategory"] = paginator.page(paginator.num_pages)

        return render(request, "shop/subcategory-product.html", context)


class ProductDetailsView(DetailView):
    model = Product
    context_object_name = "product"
    pk_url_kwarg = "pk_product"
    template_name = "shop/product-details.html"


class AddProductToSessionView(View):
    def get(self, request):
        next_page = request.POST.get("next", "/")
        return HttpResponseRedirect(next_page)

    def post(self, request):
        request.session.modified = True
        if "products" not in request.session:
            request.session["products"] = []
        if "amount" not in request.session:
            request.session["amount"] = {}
        next_page = request.POST.get("next", "/cart")
        pk_product = request.POST.get("product_id")
        request.session["products"].append(int(pk_product))
        if pk_product not in request.session["amount"].keys():
            request.session["amount"].update({pk_product: 1})
        else:
            for pk_in_dict, value in request.session["amount"].items():
                if pk_product == pk_in_dict:
                    first_item = Product.objects.values_list("amount").get(
                        id=pk_product
                    )[0]
                    if 20 > value <= first_item:
                        request.session["amount"].update({pk_product: value + 1})
                    elif value > first_item:
                        messages.info(request, "В наличии нету товаров")
                    else:
                        messages.info(request, "Limit - 20 items")
        return HttpResponseRedirect(next_page)


class RemoveProductFromSessionView(View):
    def get(self, request):
        next_page = request.POST.get("next", "/")
        return HttpResponseRedirect(next_page)

    def post(self, request):
        request.session.modified = True
        next_page = request.POST.get("next", "/cart")
        pk_product = request.POST.get("product_id")
        request.session["products"].remove(int(pk_product))
        quantity = request.session["amount"].get(pk_product)
        request.session["amount"].update({pk_product: quantity - 1})
        if request.session["amount"].get(pk_product) == 0:
            request.session["amount"].pop(pk_product)
        return HttpResponseRedirect(next_page)


class RemoveAllProductsFromSession(View):
    def get(self, request):
        return HttpResponseRedirect(request.POST.get("next", "/"))

    def post(self, request):
        request.session.modified = True
        if request.session.get("products", []):
            request.session["products"].clear()
            request.session["amount"].clear()
        return HttpResponseRedirect(request.POST.get("next", "/cart"))


class CartView(View):
    def get(self, request):
        if request.session.get("products"):
            products, total_price, amount = products_total_price_amount(request)
            amount_all = request.session.get("amount", {})
            context = {
                "products": products,
                "total_price": total_price,
                "amount_all": amount_all,
            }
            return render(request, "shop/cart.html", context)
        else:
            return render(request, "shop/cart.html")


class MakeOrderView(View):

    template_name = "shop/order.html"

    def get(self, request):
        form = OrderForm()
        return render(
            request,
            self.template_name,
            {"form": form, "products": request.session.get("products", [])},
        )

    def post(self, request):
        form = OrderForm(request.POST)
        if form.is_valid():
            name = request.POST.get("name_user")
            phone_number = request.POST.get("phone_number")
            email = request.POST.get("email_user")
            products, total_price, amount = products_total_price_amount(request)
            products = [product.id for product in products]
            remove_amount_products_from_db(request)
            if request.user.is_authenticated:
                form.save(commit=False)
                form.instance.user = request.user
            form.instance.product_ids = str(products)
            form.instance.total_price = total_price
            form.instance.total_count = amount
            form.save()
            message, html = answer_email(request, name, phone_number, total_price)
            send_message_on_email.delay(
                subject="Your order",
                message=message,
                from_email=EMAIL_HOST_USER,
                recipient_list=[email],
                html_message=html,
            )
            messages.success(request, "We'll call you!")
            remove_all_products_from_session(request)
            return HttpResponseRedirect("/")

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block metatags %}
        <meta name="description"
              content="django-shop-test.herokuapp.com">
        <meta name="keywords" content="Интернет магазин">
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'shop/js/jquery-slim.min.js' %}">
    <link rel="stylesheet" href="{% static 'shop/js/jquery-3.2.1.slim.min.js' %}">
    <link rel="stylesheet" href="{% static 'shop/js/popper.min.js' %}">
    <link rel="stylesheet" href="{% static 'shop/js/bootstrap.min.js' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'shop:index' %}">JustShop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop:cart' %}">Cart</a>
            </li>

            {% for category in menu_categories %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ category.title }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for subcategory in  category.subcategories.all %}
                            <a class="dropdown-item"
                               href="{% url 'shop:subcategory_product' subcategory.id %}">
                                {{ subcategory.title }}
                            </a>
                        {% endfor %}
                    </div>
                </li>
            {% endfor %}
        </ul>
        <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            <a class="dropdown-item" href="{% url 'auth_app:main_user_page' %}">My account</a>
                            <a class="dropdown-item" href="{% url 'auth_app:password_change' %}">Change password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'auth_app:logout' %}">Log out</a>
                        </div>
                    </li>
                </ul>
            {% else %}
                <form class="form-inline ml-auto">
                    <a href="{% url 'auth_app:login' %}" class="btn btn-outline-secondary">Log in</a>
                    <a href="{% url 'auth_app:signup' %}" class="btn btn-primary ml-2">Sign up</a>
                </form>
            {% endif %}
        </div>
    </div>
</nav>



{% block content %}
{% endblock %}

{% block messages %}
    <div class="d-flex justify-content-center">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

<footer>
    <div class="text-center fixed-bottom">
        {% block  copyright %}
            <p>&copy; 2018, <a href="mailto:onlyimholol@gmail.com">Olexandr Datsenko</a></p>
        {% endblock %}
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>