auth_app/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import signup, main_user_page

app_name = 'auth_app'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='auth_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('main/', main_user_page, name='main_user_page'),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='auth_app/password_reset.html',
            email_template_name='auth_app/password_reset_email.html',
            subject_template_name='auth_app/password_reset_subject.txt',
            success_url='done/',
            # success_url=reverse_lazy('auth_app/password_reset_done'),
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='auth_app/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='auth_app/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='auth_app/password_reset_complete.html'),
        name='password_reset_complete'),
    #
    url(r'^settings/password/$',
        auth_views.PasswordChangeView.as_view
        (template_name='auth_app/password_change.html',
         success_url='done/'
         ),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='auth_app/password_change_done.html'),
        name='password_change_done'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from django.conf.urls import include, url
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('auth_app.urls')),
    path('api/v0/', include('api_v0.urls')),
    path('debug/', include(debug_toolbar.urls))
]

shop/urls.py
from django.conf.urls import url

from .views import *
from .api import api

app_name = 'shop'
urlpatterns = [
    url(r'^$', IndexListView.as_view(), name='index'),
    url(r'^subcategory/(?P<pk_subcategory>\d+)/$', SubcategoryProductListView.as_view(),
        name='subcategory_product'),
    url(r'^subcategory/(?P<pk_product>\d+)/details/$', ProductDetailsView.as_view(),
        name='product_details'),
    url(r'^add-to-session/$', AddProductToSessionView.as_view(),
        name='add_to_session'),
    url(r'^remove-product-from-session/$', RemoveProductFromSessionView.as_view(),
        name='remove_from_session'),
    url(r'^remove-all-products-from-session/$', RemoveAllProductsFromSession.as_view(),
        name='remove_all_products'),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^order/$', MakeOrderView.as_view(), name='order'),
    url(r'^api/$', api),
]

auth_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

auth_app/views.py
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, \
    login as auth_login
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm

from shop.models import Order


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return HttpResponseRedirect('/')
    else:
        form = SignUpForm()
    return render(request, 'auth_app/signup.html', {'form': form})


@login_required(redirect_field_name='login')
def main_user_page(request):
    orders = Order.objects.filter(user=request.user.id)
    context = {'orders': orders}
    return render(request, 'auth_app/main_user_page.html', context)

auth_app/templates/auth_app/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Log in</h3>
                    <form method="post" novalidate>
                    {% csrf_token %}
                        {% include 'auth_app/includes/form.html' %}
                        <button type="submit" class="btn btn-primary btn-block">Log in</button>
                    </form>
                </div>
                <div class="card-footer text-muted text-center">
                    New to Django Boards? <a href="{% url 'auth_app:signup' %}">Sign up</a>
                </div>
            </div>
            <div class="text-center py-2">
                <small>
                    <a href="#" class="text-muted">Forgot your password?</a>
                </small>
            </div>
        </div>
    </div>
{% endblock %}

auth_app/templates/auth_app/main_user_page.html
{% extends 'base.html' %}

{% block content %}
    MAIN user page {{ user.username }} <br>
    {% for foo in orders %}
        {{ foo.name_user }}
        {{ foo.order_date }}
        {{ foo.total_price }} <br>
{#        {{ foo.product_ids }} <br>#}
    {% endfor %}

{% endblock %}

auth_app/templates/auth_app/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'auth_app/includes/form.html' %}
                    <button type="submit" class="btn btn-success">Change password</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

auth_app/templates/auth_app/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'auth_app:password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'shop:index' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

auth_app/templates/auth_app/password_reset.html
{% extends 'base.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Reset your password</h3>
                    <p>Enter your email address and we will send you a link to reset your password.</p>
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {#                    {% if field.help_text %}#}
                                {#                        <small style="color: grey">{{ field.help_text }}</small>#}
                                {#                    {% endif %}#}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

auth_app/templates/auth_app/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'auth_app:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

auth_app/templates/auth_app/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}
    {% if validlink %}
        Change password for {{ form.user.username }}
    {% else %}
        Reset your password
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card">
                <div class="card-body">
                    {% if validlink %}
                        <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
                        <form action="{% url "auth_app:password_reset_complete" %}" method="post" novalidate>
                            {% csrf_token %}
                            {% include 'auth_app/includes/form.html' %}
                            <button type="submit" class="btn btn-success btn-block">Change password</button>
                        </form>
                    {% else %}
                        <h3 class="card-title">Reset your password</h3>
                        <div class="alert alert-danger" role="alert">
                            It looks like you clicked on an invalid password reset link. Please try again.
                        </div>
                        <a href="{% url 'auth_app:password_reset' %}" class="btn btn-secondary btn-block">Request a new
                            password reset link</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

auth_app/templates/auth_app/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Reset your password</h3>
                    <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes,
                        check your spam folder.</p>
                    <a href="{% url 'auth_app:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

auth_app/templates/auth_app/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'auth_app:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team

auth_app/templates/auth_app/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <h2>Sign up</h2>
                <form method="post">
                    {% csrf_token %}
                    {% include 'auth_app/includes/form.html' %}
                    <button type="submit" class="btn btn-primary">Create an account</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}