base/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from django.conf.urls import include, url
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('auth_app.urls')),
    path('api/v0/', include('api_v0.urls')),
    path('debug/', include(debug_toolbar.urls))
]

shop/urls.py
from django.conf.urls import url

from .views import *
from .api import api

app_name = 'shop'
urlpatterns = [
    url(r'^$', IndexListView.as_view(), name='index'),
    url(r'^subcategory/(?P<pk_subcategory>\d+)/$', SubcategoryProductListView.as_view(),
        name='subcategory_product'),
    url(r'^subcategory/(?P<pk_product>\d+)/details/$', ProductDetailsView.as_view(),
        name='product_details'),
    url(r'^add-to-session/$', AddProductToSessionView.as_view(),
        name='add_to_session'),
    url(r'^remove-product-from-session/$', RemoveProductFromSessionView.as_view(),
        name='remove_from_session'),
    url(r'^remove-all-products-from-session/$', RemoveAllProductsFromSession.as_view(),
        name='remove_all_products'),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^order/$', MakeOrderView.as_view(), name='order'),
    url(r'^api/$', api),
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models

from base import settings


class Category(models.Model):
    title = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title


class Subcategory(models.Model):
    category = models.ManyToManyField(Category, related_name="subcategories")
    title = models.CharField(max_length=200, db_index=True)

    class Meta:
        verbose_name_plural = "Subcategories"

    def __str__(self):
        return self.title


class Currency(models.Model):
    name_currency = models.CharField(max_length=10, default="USD")
    UAH = models.CharField(max_length=3, default="UAH")
    currency_exchange = models.DecimalField(max_digits=8, decimal_places=0, default=25)

    class Meta:
        verbose_name_plural = "Currencies"

    def __str__(self):
        return self.name_currency


class Product(models.Model):
    subcategory = models.ManyToManyField(Subcategory)
    currency_pk = models.ForeignKey(Currency, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    description = models.TextField()
    amount = models.IntegerField(default=20)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    image_url = models.CharField(
        max_length=100, default="https://s3.amazonaws.com/django-shop-stuff/"
    )
    on_the_main = models.BooleanField(default=False)
    sku = models.CharField(max_length=10, default="200000")
    meta_keywords = models.CharField(max_length=100, db_index=True, blank=True)
    meta_description = models.CharField(max_length=1000, db_index=True, blank=True)

    __text_desription = """{} - 
     купить на django-shop-test.herokuapp.com: 
    050 123 45 67. Оперативная доставка 
    Гарантия качества
    Лучшая цена $ """

    def save(self, *args, **kwargs):
        if not self.meta_keywords or not self.meta_description:
            self.meta_keywords = self.title
            self.meta_description = self.__text_desription.format(self.title)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_total_price_in_ua(self):
        return self.price * self.currency_pk.currency_exchange


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    product_fk = models.ManyToManyField(Product)
    name_user = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=20)
    email_user = models.EmailField(max_length=100)
    total_price = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total_count = models.IntegerField()
    order_date = models.DateTimeField(auto_now_add=True)
    product_ids = models.CharField(max_length=200)

    def __str__(self):
        return self.name_user

shop/forms.py
from django import forms
from django.forms import ModelForm, CharField

from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["name_user", "phone_number", "email_user"]
        labels = {"name_user": ("Your name")}
        help_texts = {"name_user": ("Your full name")}
        error_messages = {"name_user": {"max_length": ("This writer's name is too long.")}}

shop/views.py
from base.settings import EMAIL_HOST_USER
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, View

from .forms import OrderForm
from .for_email import answer_email
from .helpers import (
    products_total_price_amount,
    remove_amount_products_from_db,
    remove_all_products_from_session,
)
from .models import Product, Subcategory, Order
from .tasks import send_message_on_email


class IndexListView(ListView):
    queryset = Product.objects.filter(on_the_main=True).order_by("id")
    context_object_name = "products"
    template_name = "shop/index.html"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        page = self.request.GET.get("page", 1)
        paginator = Paginator(self.queryset, self.paginate_by)
        context = {}
        try:
            products_on_page = paginator.page(page)
            context = {
                "subcategory": products_on_page,
                "products": self.request.session.get("products", []),
                "amount_each": self.request.session.get("amount", {}),
            }
        except PageNotAnInteger:
            context["subcategory"] = paginator.page(1)
        except EmptyPage:
            context["subcategory"] = paginator.page(paginator.num_pages)

        return context


class SubcategoryProductListView(ListView):
    def get(self, request, pk_subcategory):
        products_in_subcategory = (
            Product.objects.select_related("currency_pk")
            .filter(subcategory__in=pk_subcategory)
            .order_by("id")
        )
        page = request.GET.get("page", 1)
        paginator = Paginator(products_in_subcategory, 6)
        context = {}
        # UAH = products_in_subcategory.select_related('currency_pk').filter(UAH='UAH')
        try:
            products_on_page = paginator.page(page)
            context = {
                "subcategory": products_on_page,
                "subcategory_name": get_object_or_404(Subcategory, id=pk_subcategory),
                "products": request.session.get("products", []),
                "amount_each": request.session.get("amount", {}),
            }
        except PageNotAnInteger:
            context["subcategory"] = paginator.page(1)
        except EmptyPage:
            context["subcategory"] = paginator.page(paginator.num_pages)

        return render(request, "shop/subcategory-product.html", context)


class ProductDetailsView(DetailView):
    model = Product
    context_object_name = "product"
    pk_url_kwarg = "pk_product"
    template_name = "shop/product-details.html"


class AddProductToSessionView(View):
    def get(self, request):
        next_page = request.POST.get("next", "/")
        return HttpResponseRedirect(next_page)

    def post(self, request):
        request.session.modified = True
        if "products" not in request.session:
            request.session["products"] = []
        if "amount" not in request.session:
            request.session["amount"] = {}
        next_page = request.POST.get("next", "/cart")
        pk_product = request.POST.get("product_id")
        request.session["products"].append(int(pk_product))
        if pk_product not in request.session["amount"].keys():
            request.session["amount"].update({pk_product: 1})
        else:
            for pk_in_dict, value in request.session["amount"].items():
                if pk_product == pk_in_dict:
                    first_item = Product.objects.values_list("amount").get(
                        id=pk_product
                    )[0]
                    if 20 > value <= first_item:
                        request.session["amount"].update({pk_product: value + 1})
                    elif value > first_item:
                        messages.info(request, "В наличии нету товаров")
                    else:
                        messages.info(request, "Limit - 20 items")
        return HttpResponseRedirect(next_page)


class RemoveProductFromSessionView(View):
    def get(self, request):
        next_page = request.POST.get("next", "/")
        return HttpResponseRedirect(next_page)

    def post(self, request):
        request.session.modified = True
        next_page = request.POST.get("next", "/cart")
        pk_product = request.POST.get("product_id")
        request.session["products"].remove(int(pk_product))
        quantity = request.session["amount"].get(pk_product)
        request.session["amount"].update({pk_product: quantity - 1})
        if request.session["amount"].get(pk_product) == 0:
            request.session["amount"].pop(pk_product)
        return HttpResponseRedirect(next_page)


class RemoveAllProductsFromSession(View):
    def get(self, request):
        return HttpResponseRedirect(request.POST.get("next", "/"))

    def post(self, request):
        request.session.modified = True
        if request.session.get("products", []):
            request.session["products"].clear()
            request.session["amount"].clear()
        return HttpResponseRedirect(request.POST.get("next", "/cart"))


class CartView(View):
    def get(self, request):
        if request.session.get("products"):
            products, total_price, amount = products_total_price_amount(request)
            amount_all = request.session.get("amount", {})
            context = {
                "products": products,
                "total_price": total_price,
                "amount_all": amount_all,
            }
            return render(request, "shop/cart.html", context)
        else:
            return render(request, "shop/cart.html")


class MakeOrderView(View):

    template_name = "shop/order.html"

    def get(self, request):
        form = OrderForm()
        return render(
            request,
            self.template_name,
            {"form": form, "products": request.session.get("products", [])},
        )

    def post(self, request):
        form = OrderForm(request.POST)
        if form.is_valid():
            name = request.POST.get("name_user")
            phone_number = request.POST.get("phone_number")
            email = request.POST.get("email_user")
            products, total_price, amount = products_total_price_amount(request)
            products = [product.id for product in products]
            remove_amount_products_from_db(request)
            if request.user.is_authenticated:
                form.save(commit=False)
                form.instance.user = request.user
            form.instance.product_ids = str(products)
            form.instance.total_price = total_price
            form.instance.total_count = amount
            form.save()
            message, html = answer_email(request, name, phone_number, total_price)
            send_message_on_email.delay(
                subject="Your order",
                message=message,
                from_email=EMAIL_HOST_USER,
                recipient_list=[email],
                html_message=html,
            )
            messages.success(request, "We'll call you!")
            remove_all_products_from_session(request)
            return HttpResponseRedirect("/")

shop/templates/shop/cart.html
{% extends 'base.html' %}
{% load shop_tags %}

{% block title %}Cart{% endblock %}

{% block content %}
    <div class="container">

        <form action="{% url 'shop:remove_from_session' %}" method="POST">
            {% csrf_token %}
            {% if products %}

                <table class='table table-striped'>
                <thead>
                <tr>
                    <th>Name of item</th>
                    <th>Quantity</th>
                    <th>Price</th>
                </tr>
                </thead>
            {% endif %}

            {% for product in products %}
                <tbody>
                <tr>
                    <td>{{ product.title }}</td>
                    <td> {{ amount_all|get_item:product.id }}</td>
                    <td>{{ product.get_total_price_in_ua }} {{ product.currency_pk.UAH }}</td>
                    <td>
                        <button type="submit" class="btn btn-primary">x</button>
                    </td>
                </tr>
                </tbody>
                <input type="hidden" name="next" value="{{ request.path }}">
                <input type="hidden" name="product_id" value="{{ product.id }}">
            {% endfor %}
            </table>
        </form>


        {% if products %}
            Total_price:{{ total_price }} {{ product.currency_pk.UAH }} <br>
            Total_count:{{ amount_all|get_sum_values }} <br>
            <form action="{% url 'shop:remove_all_products' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button type="submit" class="btn btn-primary">remove all products</button>
            </form>
            <a href="{% url 'shop:order' %}" class="btn btn-primary">Перейти на форму заказа</a>
        {% else %}
            <div class="d-flex justify-content-center">
                <h3>Your cart is empty</h3>
            </div>
        {% endif %}
    </div>
{% endblock %}

shop/templates/shop/for_email.html
{% load shop_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Your order, {{ name }}</h3>

<table class="table-dark" border="2">
    <tr>
        <th>Name of item</th>
        <th>Quantity</th>
        <th>Price</th>
    </tr>
    {% for product in products %}
        <tr>
            <td>{{ product.title }}</td>
            <td> {{ amount_all|get_item:product.id }}</td>
            <td>{{ product.get_total_price_in_ua }} UAH</td>
        </tr>
    {% endfor %}
</table>
Price of all items- {{ total_price }} UAH
</body>
</html>

shop/templates/shop/index.html
{% extends 'base.html' %} 
{% load shop_tags %} 
{% block title %}Main Products{% endblock %} 
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <h3> New products </h3>
        </div>
    </div>

    <div class="row text-center">
        {% for product in subcategory %}
        <div class="col-xs-12 col-sm-4 col-lg-4">
            <img src="{{ product.image_url }}" alt="fly" width="100" height="100">
            <hr>
            <a href="{% url 'shop:product_details' product.id %}">{{ product.title }}</a>
            <br> {{ product.get_total_price_in_ua }} {{ product.currency_pk.UAH }}
            <form action="{% url 'shop:add_to_session' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <input type="hidden" name="amount" value="{{ product.amount }}">

                <button type="submit" class="btn btn-primary">Add to the cart!</button>
            </form>

            {% if product.id in products %}
            <form action="{% url 'shop:remove_from_session' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <button type="submit" class="btn btn-primary">Remove from the cart!</button>
            </form>
            Already in the cart -- {{ amount_each|get_item:product.id }} {% endif %}
        </div>
        {% endfor %}
    </div>
</div>
<br>
<div class="container col-1 text-center ">
    <div class="pagination">
        {% if subcategory.has_other_pages %}
        <ul class="pagination ">
            {% if subcategory.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ subcategory.previous_page_number }}">&laquo;</a>
            </li>
            {% endif %} {% for i in subcategory.paginator.page_range %} {% if subcategory.number == i %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }} </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }} </a>
            </li>
            {% endif %} {% endfor %} {% if subcategory.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ subcategory.next_page_number }}">&raquo;</a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

shop/templates/shop/order.html
{% extends "base.html" %}

{% block content %}
    {% if products %}
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-lg-3">
                    <form action="{% url 'shop:order' %}" method="POST">
                        <div class="form-group ">
                            <table class="table">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group">
                                        {{ field.label_tag }}
                                        {{ field }}
                                        {% if form.errors %}
                                            {% for error in form.non_field_errors %}
                                                <div class="alert alert-danger">
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                        {% if field.help_text %}
                                            <small class="form-text text-muted">
                                                {{ field.help_text|safe }}
                                            </small>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </table>
                            <input type="submit" class="btn btn-primary" value="Make order"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        Add items to cart, please)
    {% endif %}


{% endblock %}

shop/templates/shop/product-details.html
{% extends 'base.html' %}

{% block metatags %}
    <meta name="keywords" content="{{ product.meta_keywords }}">
    <meta name="description" content="{{ product.meta_description }}">
{% endblock %}
{% block title %}{{ product.title }}{% endblock %}


{% block content %}
    <div class="container">
        <div class="col text-center"><h3>{{ product.title }}</h3></div>
        <div class="row">
            <div class="col-3">
                <img src="{{ product.image_url }}"
                     alt="fly" width="200" height="200">
            </div>
            <div class="col">
                <h4> Characteristics </h4>
                Name : {{ product.title }} <br>
                Price : {{ product.get_total_price_in_ua }} <br>
                Description: <br>
                {{ product.description }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form action="{% url 'shop:cart' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <input type="hidden" name="product_id" value="{{ product.id }}">

                    <button type="submit" class="btn btn-primary">Add to cart!</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/subcategory-product.html
{% extends 'base.html' %}
{% load static %}
{% load shop_tags %}

{% block metatags %}
    <meta name="keywords" content="SmartPhone">
    <meta name="description"
          content="django-shop-test.herokuapp.com:">
{% endblock %}

{% block title %}{{ subcategory_name }}{% endblock %}


{% block content %}

    <div class="container">
        <div class="row text-center">
            <div class="col-12">
                <h1>{{ subcategory_name }}</h1>
            </div>
        </div>

        <div class="row text-center">
            {% for product in subcategory %}
                <div class="col-xs-12 col-sm-4 col-lg-4">
                    <img src="{{ product.image_url }}"
                         alt="fly" width="100" height="100">
                    <hr>
                    <a href="{% url 'shop:product_details' product.id %}">{{ product.title }}</a>
                    <br>
                    {{ product.get_total_price_in_ua }} {{ product.currency_pk.UAH }}
                    <form action="{% url 'shop:add_to_session' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <input type="hidden" name="amount" value="{{ product.amount }}">

                        <button type="submit" class="btn btn-primary">Add to the cart!</button>
                    </form>

                    {% if product.id in products %}
                        <form action="{% url 'shop:remove_from_session' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <input type="hidden" name="product_id" value="{{ product.id }}">
                            <button type="submit" class="btn btn-primary">Remove from the cart!</button>
                        </form>
                        Already in the cart -- {{ amount_each|get_item:product.id }}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
    <br>
    <div class="container col-1 text-center ">
        <div class="pagination">
            {% if subcategory.has_other_pages %}
                <ul class="pagination ">
                    {% if subcategory.has_previous %}
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ subcategory.previous_page_number }}">&laquo;</a>
                        </li>
                    {% endif %}
                    {% for i in subcategory.paginator.page_range %}
                        {% if subcategory.number == i %}
                            <li class="page-item"><a class="page-link"
                                                     href="?page={{ i }}">{{ i }} </a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link"
                                                     href="?page={{ i }}">{{ i }} </a></li>
                        {% endif %}
                    {% endfor %}
                    {% if subcategory.has_next %}
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ subcategory.next_page_number }}">&raquo;</a></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}